import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from "react";
import { Lightbox } from "@/components/Lightbox";
import images from "@/components/images";
import Styles from "../styles/Home.module.css"
import Image from 'next/image';
import { Poppins } from 'next/font/google'
const poppins = Poppins({ subsets: ["latin"], weight: ["400"] })

export default function Home() {
  const [isOpen, setIsOpen] = useState(false)
  const backgroundImage = images[0]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${Styles.Main} ${poppins.className}`}>

        <Lightbox images={images} isOpen={isOpen} close={() => setIsOpen(false)} />

        <h1>Nextjs Image Lightbox</h1>
        <div>
          <button className={styles.media_item} href="#" onClick={() => setIsOpen(true)}>
            <Image
              src={backgroundImage.image}
              alt={backgroundImage.text}
              width={200}
              height={150}
            />
            <div className={Styles.BtnText}>
              <h2>{backgroundImage?.text}</h2>
              <p>View Collection</p>
            </div>
          </button>
        </div>

      </main>
    </>
  )
}
