import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useState } from "react";
import { Lightbox } from "@/components/Lightbox";
import folder from "@/components/Galleries";
import Styles from "../styles/Home.module.css"

export default function Home() {
  const [currentGallery, setCurrentGallery] = useState(null)
  const [galleries, setGalleries] = useState([folder, folder, folder, folder, folder])


  function openLightbox(gallery) {
    setCurrentGallery(gallery)
  }

  function closeLightbox() {
    setCurrentGallery(null)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          currentGallery && <Lightbox gallery={currentGallery} close={closeLightbox} />
        }
        <div className={Styles.Grid}>
          {galleries.map((gallery, i) => {
            const randomImageIndex = Math.floor(Math.random() * gallery.length - 1)
            const backgroundImage = gallery[randomImageIndex]
            return (
              <button key={i} className={styles.media_item} href="#" onClick={() => openLightbox(gallery)}>
                <Image
                  src={backgroundImage?.Image}
                  alt={backgroundImage?.Text}
                  fill
                  sizes={"10vh"}
                />
                <div className={Styles.BtnText}>
                  <h2>{backgroundImage?.Text}</h2>
                  <h5>View Collection</h5>
                </div>
              </button>
            )
          })}
        </div>

      </main>
    </>
  )
}
